# Generated by Django 3.2.8 on 2022-03-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_cladire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('idDesk', models.AutoField(primary_key=True, serialize=False)),
                ('deskCount', models.IntegerField(blank=True, null=True)),
                ('usedDesks', models.IntegerField(blank=True, null=True)),
                ('adminOffice', models.CharField(blank=True, max_length=30, null=True)),
                ('lengthDesk', models.IntegerField(blank=True, null=True)),
                ('widthDesk', models.IntegerField(blank=True, null=True)),
                ('isOccupied', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idEmployee', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONBINARY', 'Nonbinary')], max_length=20, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('idOffice', models.AutoField(primary_key=True, serialize=False)),
                ('nameOffice', models.CharField(max_length=30)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('deskCount', models.IntegerField(blank=True, null=True)),
                ('usedDesks', models.IntegerField(blank=True, null=True)),
                ('adminOffice', models.CharField(blank=True, max_length=30, null=True)),
                ('lengthOffice', models.IntegerField(blank=True, null=True)),
                ('widthOffice', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.cladire')),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('idRemote', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(auto_now_add=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('isApproved', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='desk',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.office'),
        ),
    ]
