# Generated by Django 3.2.9 on 2022-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_auto_20220306_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
    ]
