# Generated by Django 3.2.8 on 2022-03-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_auto_20220310_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
