# Generated by Django 4.0.3 on 2022-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_alter_remote_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('OFFICEADMIN', 'Ofice Admin'), ('USER', 'User')], max_length=50, null=True),
        ),
    ]
