# Generated by Django 4.0.3 on 2022-03-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='desk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='space.desk'),
            preserve_default=False,
        ),
    ]
