# Generated by Django 4.0.3 on 2022-03-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0009_employee_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='approvedBy',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OFFICEADMIN', 'Ofice Admin'), ('USER', 'User')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
