# Generated by Django 4.0.3 on 2022-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0010_remote_approvedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='adminOffice',
            field=models.CharField(choices=[('admin', 'admin'), ('officeadmin', 'oficeadmin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='desk',
            name='deskCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desk',
            name='lengthDesk',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desk',
            name='widthDesk',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='SV', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('nonbinary', 'nonbinary')], default='male', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='romanian', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('officeadmin', 'oficeadmin'), ('user', 'user')], default='user', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='deskCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='lengthOffice',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='widthOffice',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remote',
            name='approvedBy',
            field=models.CharField(choices=[('admin', 'admin'), ('officeadmin', 'oficeadmin'), ('user', 'user')], max_length=30),
        ),
        migrations.AlterField(
            model_name='remote',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remote',
            name='startDate',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
