# Generated by Django 4.0.3 on 2022-03-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_alter_desk_adminoffice_alter_desk_deskcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
